export const musics = [
  {
    name: "Main Theme",
    author: "God of War",
    url: require("./../assets/godOfWar.png"),
    isActive: false,
    liked: false,
    id: 1,
  },
  {
    name: "Married Life",
    author: "Up altas aventuras",
    url: require("./../assets/up.png"),
    isActive: false,
    liked: false,
    id: 2,
  },
  {
    name: "Enemy",
    author: "Arcane",
    url: require("./../assets/arcane.png"),
    isActive: false,
    liked: false,
    id: 3,
  },
  {
    name: "Ticking Away",
    author: "Valorant",
    url: require("./../assets/valorant.png"),
    isActive: false,
    liked: false,
    id: 4,
  },
  {
    name: "Sunflower",
    author: "Homem aranha- Aranhav...",
    url: require("./../assets/homem-aranha.png"),
    isActive: false,
    liked: false,
    id: 5,
  },
  {
    name: "Heathens",
    author: "Suicide Squad",
    url: require("./../assets/suicide-squad.png"),
    isActive: false,
    liked: false,
    id: 6,
  },
]

export const musicsLiked = [
  {
    name: "Ticking Away",
    author: "Valorant",
    url: require("./../assets/valorant.png"),
    isActive: true,
    liked: true,
    id: 1,
  },
  {
    name: "Sunflower",
    author: "Homem aranha- Aranhav...",
    url: require("./../assets/homem-aranha.png"),
    isActive: true,
    liked: true,
    id: 2,
  },
  {
    name: "Heathens",
    author: "Suicide Squad",
    url: require("./../assets/suicide-squad.png"),
    isActive: true,
    liked: true,
    id: 3,
  },
]